sudo: true
os: trusty
cache: false
env:
- URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
before_install:
- openssl aes-256-cbc -K $encrypted_b1fbf710b918_key -iv $encrypted_b1fbf710b918_iv
  -in assets/server.key.enc -out assets/server.key -d
- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG
- mkdir sfdx
- wget -qO- $URL | tar xJ -C sfdx --strip-components 1
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx --version
- sfdx plugins --core
- sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key
  --username $USERNAME --setdefaultdevhubusername -a HubOrg
script:
- sfdx force:org:create -v HubOrg -s -f config/project-scratch-def.json -a ciorg --wait
  2
- sfdx force:org:display -u ciorg
- sfdx force:source:push -u ciorg
- sfdx force:apex:test:run -u ciorg --wait 10
- sfdx force:org:delete -u ciorg -p
dd:
  secure: SBRmCCmUbVuA0j26nr8H2R2KzozcW/Rut6LyrdkUiGz5aTaU3Klbloet+DJCH5f+g8QNLOFJ+Wq6BHgrFrnG35AKMzcLPaXKccb3JBBD/GmhfHM9S4GtElhTpyHqf66I6nGtjFHCZU+id9m8vqKDxdxTe0QQnNCMHywfBjTi3YKP/TJm7XIByy9GAdXcqnIjFFOAQ5d19Tq+kHGfUlOnPGaVkiOCpKjfH4abWaItkIR2jYcwER1D+xFnNeKsqLAjTHfNJtg8w+lzCzobnHx6PnSMuB4Xf2cXxph0EfMrvoeKu377oUtdN7nO7YA3JXtZQUztTte1w/QGoE+cphhARwg/qrb5VQDUPs7lP/Un9etAHXr1hkJ8kxzdAif3LhkfKOt0ayvscVZUj4nfA8gvWhI2zhTxaAKiaRdvNWfgCtUG1Z+Ae7eLzqXlbjze3Bsu63HK/F2LlGB8XMIyE0gGffSLP4qqMPwNyHTsRY8czo2pJko+h6tlOZYMx1lt0wzWLJIrrmPnTXvLLjcbcWaJZFtylrP5C+/Lb7/Q2wIGsAn793BYUUHEsZ0hj/8Np/Rvlym8cbyOpW3kNIZl3jm3+86KrM97D//olXta7rgjPvRk494/W1LHhTYLJsSsOu/faPNZXkCqtS5s1VTQR3nQqHXSH0FmzKiw0VmU8IF4i50=
